spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.100:5432/library
    username: librarian
    password: lib@!12

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
