spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/library
    username: library_user
    password: library@!

  jpa:
    show-sql: true          # SQL 출력
    properties:
      hibernate:
        format_sql: true    # 보기 좋게 포맷팅
